version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: votesphere
    networks:
      - votesphere-networks

  test-db:
    image: postgres:13
    ports:
      - "8000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: votesphere
    networks:
      - votesphere-networks

networks:
  votesphere-networks:
    driver: bridge

